### ISSUE TITLE
Re-add lastScreen to recording descriptions

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#185]
we used to include a screenshot in the recording descriptions. It would be nice to re-add it.

**Comment by bhackett1024** [comment]
So, in the V1 recorder we were able to generate the last screen in the middleman process, since graphics were drawn into a buffer in that process and we could extract the graphics data and convert it to a base64-encoded JPEG when saving the recording.  With the V2 recorder, there isn't a middleman process anymore; the recording process just uses the regular drawing paths for a content process.  So, we need a new way of getting the tab's contents.  It looks like there are a number of ways to do this in Firefox [1] [2], but I haven't used any of them and some experimentation will be needed.  This could be done either within the recording process when it sends its RecordingFinished notification (see devtools/server/actors/replay/module.js), or from the UI process in devtools/startup/DevToolsStartup.jsm when it receives that notification.

[1] https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureTab
[2] https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawWindow

**Comment by jasonLaster** [comment]
it _might_ be this simple...

```diff
diff --git a/devtools/server/actors/replay/module.js b/devtools/server/actors/replay/module.js
index 67b5a6639d07..eb83b8dae475 100644
--- a/devtools/server/actors/replay/module.js
+++ b/devtools/server/actors/replay/module.js
@@ -358,6 +358,25 @@ function eventListener(info) {
     RecordReplayControl.onEvent(event, info.phase == "pre");
   }
 }
+function getWindowAsImageData(win) {
+  const canvas = win.document.createElementNS(
+    "http://www.w3.org/1999/xhtml",
+    "canvas"
+  );
+  const scale = getCurrentZoom(win);
+  const width = win.innerWidth;
+  const height = win.innerHeight;
+  canvas.width = width * scale;
+  canvas.height = height * scale;
+  canvas.mozOpaque = true;
+
+  const ctx = canvas.getContext("2d");
+
+  ctx.scale(scale, scale);
+  ctx.drawWindow(win, win.scrollX, win.scrollY, width, height, "#fff");
+
+  return ctx.getImageData(0, 0, canvas.width, canvas.height);
+}

 function SendRecordingFinished(recordingId) {
   const document = getWindow().document;
@@ -366,6 +385,8 @@ function SendRecordingFinished(recordingId) {
     url: document.URL,
     title: document.title,
     duration: new Date() - startTime,
+    lastScreenData: getWindowAsImageData(getWindow()),
+    lastScreenMimeType: "jpeg",
   };
   Services.cpmm.sendAsyncMessage("RecordingFinished", data);
 }
```
