### ISSUE TITLE
Improve cancel recordings flow

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#232]
Currently it's not obvious how users should stop recording, without saving. 

* One easy option would be to add a cancel button
* The current way is to close the tab via cmd+w or clicking the close button, but that might be too hidden

The downside with closing the tab is that you would have to copy the url to then go back to that page

**Comment by ryanjduffy** [comment]
@jasonLaster - I think this is generally covered by the combination of opening in a new tab to preserve the current tab and the new upload screen which provides a discard button.

A related "bug" is that the discard flow will reload the source tab but that isn't really relevant since it has been opened in a new tab. Perhaps that should be redirecting to the library. Thoughts?

**Comment by jasonLaster** [comment]
yep. i think it should probably redirect to the library, but agreed. this feels done.
