### ISSUE TITLE
Replay does not install for security reasons

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#240]
<img width="352" alt="Screen Shot 2020-12-08 at 8 25 30 PM" src="https://user-images.githubusercontent.com/254562/101585048-d5826380-3993-11eb-8071-c9b0c711533b.png">

**Comment by bhackett1024** [comment]
So, we notarize the binaries we release with apple so that it is supposed to let users open the downloaded app without using special workarounds.  I just tried this on my machine to see if it is working.  After deleting the replay app, my STR:

1. Download from https://replay.io/downloads/replay.dmg
2. Open downloaded DMG, drag replay => applications
3. Open replay app from launchpad

I get this screen:

<img width="502" alt="Screen Shot 2020-12-09 at 5 04 38 AM" src="https://user-images.githubusercontent.com/1062578/101627937-536a5d00-39dc-11eb-85b1-154abbec3bab.png">

This is what is supposed to happen.  Clicking open opens the application, and trying to open it later doesn't show any message first.  Some thoughts:

1. It would be nice to know if this problem is still happening for the person, maybe it was some transient problem with Apple's servers.

2. I'm not sure what happens when opening the application for the first time when there isn't an internet connection.  I just tried again with my internet connection disabled and see the same screen, but maybe the notarization information was cached on disk after it was downloaded earlier.

We don't go through the full notarization process with apple.  We submit the app for notarization and check that process succeeds, but after that succeeds apple gives us something we can use to staple to the DMG and IIUC allow apps to open without contacting apple's servers.  We don't do that, and maybe doing it would fix things for this person.  More info:

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

As far as workarounds, other than disabling gatekeeper entirely I was able to open the app for the first time without getting the warning above by starting it from the terminal (`/Applications/Replay.app/Contents/MacOS/replay`).

**Comment by jazzdan** [comment]
@jasonLaster do we know what version of macOS they were on? I imagine we're not testing with Big Sur and I wonder if that flow has changed a little bit in the new version.

**Comment by bendtherules** [comment]
I was the reporter. 
I'll check the machine & cli details and get back.

**Comment by jasonLaster** [comment]
@trysound reported a similar issue today
```
Cannot open replay. After verifying get this.
And nothing in "security and privacy".
I'm on mac os mojave.
```

![](https://cdn.discordapp.com/attachments/798693728999047203/811344425774481459/unknown.png)

**Comment by jasonLaster** [comment]
@bhackett1024 


> I think that opening it from the terminal like /Applications/Replay.app/Contents/MacOS/replay might act as a workaround (definitely not a solution though)

**Comment by jasonLaster** [comment]
@jonbell-lot23 
> And in some cases right-clicking to select Open works:

![](https://cdn.discordapp.com/attachments/798693728999047203/811346674718212126/unknown.png)

**Comment by jasonLaster** [comment]
right clicking worked for @trysound :)

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-185](https://linear.app/replay/issue/RUN-185/replay-does-not-install-for-security-reasons)
