### ISSUE TITLE
cannot save a recording of twitter.com

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#263]
STR:
1. go to twitter.com
2. press record
3. press save

https://www.loom.com/share/7a1aec0a554f445ba100e8a9561cd9d5

**Comment by bhackett1024** [comment]
The problem here is that while loading the page the browser switches from the recording content process to an existing one which doesn't record.  The attribute state we use to see if the tab is recording stays the same, so we think the tab is recording when it really isn't, and nothing happens when we try to stop the recording.  The attached patch fixes this by disallowing the initial switch, except when we are recording all content processes anyways.
