### ISSUE TITLE
Popup blocker interrupts onboarding flow

### ISSUE THREAD

**Issue by lisahackett1978** [replayio/gecko-dev#275]
Steps to reproduce
1. Start with a fresh Replay installation and new firefox profile

2. Launch Replay, sign in using google credentials

3. Window appears "Replay prevented the site from opening 2 popup windows"
<img width="1440" alt="Screen Shot 2021-01-14 at 2 11 02 PM" src="https://user-images.githubusercontent.com/77456982/104815010-47d63700-57cf-11eb-827f-ff9069973614.png">

4. Click "Preferences", select "Allow Popups for replay.io"

5. A mini screen comes up, it's blank
<img width="428" alt="Screen Shot 2021-01-14 at 9 09 07 AM" src="https://user-images.githubusercontent.com/77456982/104815104-d6e34f00-57cf-11eb-8982-4fecdb2e689b.png">

6. Close mini screen, encounter another screen "Whoops, please turn off your popup blocker"
<img width="641" alt="Screen Shot 2021-01-16 at 7 30 24 AM" src="https://user-images.githubusercontent.com/77456982/104815188-4d804c80-57d0-11eb-9764-bd1588ca16fa.png">

7. Finally, refresh and see the expected screen
<img width="1440" alt="Screen Shot 2021-01-14 at 2 15 32 PM" src="https://user-images.githubusercontent.com/77456982/104815234-8d473400-57d0-11eb-8c91-680e2011e2fd.png">

**Comment by jasonLaster** [comment]
Thanks for filing. I think we can probably update a browser pref so that `replay.io` by default allows popups.

I did some quick splunking and found this

1. the l10n string for pop-ups for [link](https://searchfox.org/mozilla-central/source/browser/locales/en-US/chrome/browser/browser.properties#277)
2. locations where popupAllow is used [link](https://searchfox.org/mozilla-central/search?q=popupAllow&redirect=false)
3. some popup toggling logic [link](https://searchfox.org/mozilla-central/source/browser/base/content/browser.js#1106-1133)

**Comment by hbenl** [comment]
This should have been fixed with RecordReplay/devtools#1552.

**Comment by lisahackett1978** [comment]
I tested this again, and it is fixed! Thank you so much.
