### ISSUE TITLE
Support Playwright

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#286]
Microsoft [Playwright](https://github.com/microsoft/playwright) [docs](https://playwright.dev/) is an alternative to Puppeteer that gaining traction. It has cross browser support (Firefox, Chromium, Safari) and cross os support (windows, mac, linux). 

If Replay supported Playwright, it would be possible to record playwright sessions and the growing number of tests run in CI.

Playwright is also in the Firefox fork [game](https://github.com/microsoft/playwright/tree/master/browser_patches/firefox), but they're playing it better than us [link](https://github.com/microsoft/playwright/commits/master/browser_patches/firefox). The latest rebase was today and it seems to be fairly frequent and fairly lightweight. However unpleasant the prospect, my guess is that applying the Playwright patches should be fairly straightforward given there is likely any overlap...

As a next step, it'd be nice to see how the patches are applied and how [build.sh](https://github.com/microsoft/playwright/blob/master/browser_patches/firefox/build.sh) is used.

**Comment by bhackett1024** [comment]
I've created a branch https://github.com/RecordReplay/gecko-dev/tree/replay-playwright which incorporates the playwright changes in our main tree.  I ran into a few minor conflicts applying the patches because playwright's patches are based on a different revision of gecko-dev.  Building in progress...

For now this is experimental, but going forward it might be good to maintain a branch that is better synced up with the playwright version of firefox so we'll have something closer to a drop in replacement.

**Comment by bhackett1024** [comment]
After some fiddling around and fixing a couple bugs (our own problems, not related to playwright) I'm able to use playwright with replay and a hello world type script (load http://whatsmyuseragent.org/, take a screenshot), recording the result.  This is only working locally right now, next we need to get things working with the production backend, which needs a few tweaks.
