### ISSUE TITLE
Todomvc crashes while recording/replaying

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#29]
here are 2 crash reports that i hit while recording/replaying https://firefox-dev.tools/debugger-examples/examples/todomvc/

https://drive.google.com/drive/u/0/folders/1oLdw6DQESOBLQfGZEjkFsYgui70R-Hbh

**Comment by bhackett1024** [comment]
Looking at these crashes, I think the problem is that the SaveCloudRecording entrypoint to the replay JS from C++ threw an exception, which caused the caller to immediately crash.  Because the JS exception was thrown in the recording process it wasn't logged, so it's hard to investigate further.  Fixing #44 will let us act on crashes like this.
