### ISSUE TITLE
[UX] Add clearer error messages for web apis

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#314]

**Comment by jasonLaster** [comment]
I think this ticket is blocked on specific examples like in #305 where replay will go white or simply crash

**Comment by bhackett1024** [comment]
Instead of replacing the tab with an error page talking about webgl, we can just show a dismissable text warning like what happens when there is a lot of JS running on the page and slowing it down.  This will handle both the case where e.g. webGL doesn't work and the page crashes and goes white, and where webGL doesn't work but the page recovers and works fine (e.g. facebook.com).  This could be refined in the future but it's important to message people about why their page isn't loading properly when recording.

**Comment by bhackett1024** [comment]
With the upcoming fix, this is what is shown when trying to view a webpage that uses unsupported features.

<img width="1281" alt="Screen Shot 2021-09-07 at 11 11 04 AM" src="https://user-images.githubusercontent.com/1062578/132398257-567c4230-a69a-462d-8b01-91db99748504.png">
