### ISSUE TITLE
Paint is wrong on replay view

### ISSUE THREAD

**Issue by kannanvijayan** [replayio/gecko-dev#341]
**Description:**
Recorded a replay session, and on playback the displayed image is wrong.

**Steps to Reproduce:**
Replay the following recording: https://replay.io/view?id=e4bf4826-bcf7-4a8c-b923-8b1cfea9bbea
Record the replay.  Then view the recording.  Observe the painting screenshot be off.

**Expected Result:**
Screenshot does not show console view obscuring the timeline view.  Timeline view is not obscured in actual UI.
 
**Additional Context:**

* Screenshots:
* 
<img width="1273" alt="Screen Shot 2021-04-13 at 4 26 32 PM" src="https://user-images.githubusercontent.com/76070462/114617013-9469cb00-9c75-11eb-96ca-3ada21a0e152.png">

* Video (Loom):
* Replay:
Original recording to use to reproduce: https://replay.io/view?id=e4bf4826-bcf7-4a8c-b923-8b1cfea9bbea
My recording that is a reproduction: https://replay.io/view?id=d1e38a09-5156-46f0-a243-9abdb9edae38

**Comment by jasonLaster** [comment]
Thanks @kannanvijayan. Transfered to gecko-dev and labeled it graphics. We have several of these overflow bugs

**Comment by bhackett1024** [comment]
I just created a new recording with the latest browser and things seem to be working.  The way that things are overflowing looks like the same issue as https://github.com/RecordReplay/gecko-dev/issues/292, which is fixed in the latest browser.

https://replay.io/view?id=ae0bddd0-f5c7-4b05-93dd-3d0ef5b8ca57
