### ISSUE TITLE
Introduce `__IS_RECORD_REPLAY_RUNTIME__`

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#343]
Having a flag in the window namespace will help the Replay Library knows if it's running in a browser capable of recording.  There are probably other use case in the future as well too...

blocks https://github.com/RecordReplay/devtools/issues/2194

**Comment by loganfsmyth** [comment]
I get not wanting to change the existing Firefox entries in user-agent, but wouldn't adding additional user-agent entries be fine, or does that break something?

**Comment by bhackett1024** [comment]
Good question, I don't know what the ramifications are of changing the U/A string.

**Comment by ryanjduffy** [comment]
I think the UA makes sense; it's what I'd have expected. I tried appending something to the UA last night but ran into a snag. Replay builds but then fails to launch. When I comment out the part I concatenated, it does launch so it's clear I broke _something_. :) Hoping someone can point me in the right direction on troubleshooting.

**Comment by kannanvijayan** [comment]
Is the user agent getting changed for all requests or just the ones to our servers?  If it's for all requests I'm concerned it might have the potential to affect site behaviour and lead to different execution patterns for recording browsers vs. the equivalent non-recording browser.

**Comment by bhackett1024** [comment]
I think if we changed in one case we'd need to change it in all cases.  That's why I originally suggested using the window property instead, but I don't know how likely U/A changes are to affect website behavior.  What is Brave's U/A string compared to chrome?

**Comment by kannanvijayan** [comment]
I don't know either, but it's not the kind of question that seems answerable by a short discussion.  I like the window property because the existence of some property with an unrecognized name on the global namespace is a routine thing in webdev.  While in principle you're not supposed to make assumptions about either UA or extra global names, in practice UA sniffing is really prevalent and global name-scanning is really rare.

Unless the window property thing presents a significant technical challenge or timeburden compared to the alternative, it's the better route.  Less chance of having to revisit this issue further down the line.
