### ISSUE TITLE
Show the upload screen as soon as the user clicks on the save button

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#384]
I am still seeing delays between clicking the save button and the new tab being created. The issue is likely on the C++, but we can probably paper over it in connection + devtoolsStartup

This video shows it taking 5 seconds to create the new replay tab
https://www.loom.com/share/23c8f8f6154c469ab4211456b863080b

**Comment by loganfsmyth** [comment]
From what I can tell, this is because the initial page render of Replay is pretty CPU intensive and blocks the main thread for a bit so it takes the recorded process a bit of time to realize that it has been told to stop recording..

I threw some logs into my local build and get roughly the following. The "CPP" lines `(TimeStamp::Now() - TimeStamp()).ToMilliseconds()` doesn't appear to be based on the unix epoch, but it does illustrate the time difference between those 2 lines fine.
```
// Clicked the button
console.log: "FINISH RECORDING" 1621983481352
// CPP "Unused << SendFinishRecording();"
CPP OUTGOING FINISH RECORDING 746247249.552887
WaitForFinishedRecording
// In "RecvFinishRecording()"
CPP INCOMING FINISH RECORDING 746253067.267204
// module.js SendRecordingFinished called
console.log: "CALL SEND RECORDING FINISH" 1621983487170
// Took ~140ms, before sending async message, I assume spent generating the window screenshot
console.log: "SENDING RECORDING FINISH" 1621983487311
// Parent process got the message that the child process finished.
console.log: "ON_FINISHED" 1621983489651
```
So you can see that the parent thread sent the `FinishRecording` message and then it took ~5.8seconds just waiting for the main thread's job queue to clear enough to process the IPDL message from the main thread telling it to shut down. It also then toom ~2 seconds for the message to go from the child process to the parent for some reason, which isn't great. Might also just be that the message queue again had stuff it was doing?

Given all that, I'm not sure we have a ton we can do here except show a spinner to the user until the recording is actually finished.

A quick profile of replay.io/view for instance shows:
<img width="2759" alt="Screen Shot 2021-05-25 at 3 33 24 PM" src="https://user-images.githubusercontent.com/132260/119579768-fbe66080-bd73-11eb-8e3e-a02ba5476886.png">

**Comment by jasonLaster** [comment]
Thanks @loganfsmyth

**Comment by jonbell-lot23** [comment]
Sounds like we can close this and track in an issue like https://github.com/RecordReplay/gecko-dev/issues/413 ?

**Comment by ryanjduffy** [comment]
We have spinners and some new telemetry so closing this out in favor of opening something new later with more actionable data.
