### ISSUE TITLE
Monitor the health of the recording tab

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#394]
The parent process should check the health of the recording tab and handle cases where the recording tab becomes unresponsive.

There are several things we should probably do
1. Send telemetry to the server
2. stop recording
3. show an error message to the user

**Comment by kannanvijayan** [comment]
Is setting a heartbeat timer on the page and waiting for long pauses in the parent a reasonable way to do detect the "unresponsive tab" scenario?

**Comment by jasonLaster** [comment]
there are probably some good ways to do it with the existing infrastructure for DevToolsStartup and Connection. It's a good question for @loganfsmyth

**Comment by loganfsmyth** [comment]
It's tough, I think "unresponsive" is a hard thing in JS, since that doesn't actually mean the page is broken, it might just take a while for one reason or another. The child itself already sends a notification if the driver decides the recording is unusable, and we already show an error to the user in that case.

It feels to like the right thing to do would be to show a spinner on the button once Stop is pressed, so once button the "Stop" is pressed, there'd be a spinner and the button is disable either until the recording is ready, or we hit some timeout like 30 seconds where we let the user know something unexpected has gone wrong.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-44](https://linear.app/replay/issue/RUN-44/monitor-the-health-of-the-recording-tab)
