### ISSUE TITLE
Improve the record button transition states

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#413]
The record button with the new spinner has some jarring transition states
https://www.loom.com/share/78d374e4eff74abeb30e1ee7e59b3d78

Here is a before and after. We should do our best to simplify this so the transitions are cleaner

<img width="1298" alt="record button" src="https://user-images.githubusercontent.com/254562/121275365-5fe34b80-c881-11eb-874b-66e5db78d4d0.png">

**Comment by ryanjduffy** [comment]
These are, at least in part, due to the lack of proper state management since we lack the correct triggers for changing the UI state. I'll take a look at this next week but want to chat with @loganfsmyth on the state mgmt side before fixing a side effect.

**Comment by jasonLaster** [comment]
Thanks @ryanjduffy. Tagging @jonbell-lot23 to get some design help on showing the transition state for starting and stopping a recording.

**Comment by jonbell-lot23** [comment]
Hey team! Here's the design we should move towards:

![image](https://user-images.githubusercontent.com/9154902/121827329-b2a08580-cd0f-11eb-8c1d-c945f7f85928.png)

Here's the design lesson to go with it:

* It's a super common mistake to wire state directly to UI, which causes flickering effects. The high level way to do this is to "assume success" and only show the loading icons after a delay.
* Technically we should use an indeterminate loader (a spinner) rather than a determinate one (progress bar) but we frequently fake it. We're going to fake it here because the circle fits in really nicely with the image and it mirrors the same visual we use in the bottom left corner with our global loader
* We need the button to have the same width in all three states so it doesn't jitter back and forth

**Comment by jasonLaster** [comment]
Thanks. I assume we should do the same for starting as well where we optimistically show the STOP button, but after a delay show a spinner if it is taking longer...

**Comment by jonbell-lot23** [comment]
>Thanks. I assume we should do the same for starting as well where we optimistically show the STOP button, but after a delay show a spinner if it is taking longer...

Totally agree, here's a new visual to represent that:
![image](https://user-images.githubusercontent.com/9154902/121964125-277ec880-cdbf-11eb-9f38-083f166922fe.png)

**Comment by ryanjduffy** [comment]
Doesn't appear that any of the tabbrowser instance, the frameloader, or the remoteTab is a persistent reference when dragging the tab into a new window so still looking for a candidate to key the state management.

cc: @loganfsmyth

**Comment by loganfsmyth** [comment]
Hmm, are you sure? I just applied this patch locally:
```diff
diff --git a/devtools/startup/DevToolsStartup.jsm b/devtools/startup/DevToolsStartup.jsm
index 235c2b74a272..2e1455f95c37 100644
--- a/devtools/startup/DevToolsStartup.jsm
+++ b/devtools/startup/DevToolsStartup.jsm
@@ -1766,6 +1766,10 @@ function onRecordingStarted(recording) {
     return browser;
   }
 
+  const initialBrowser = getBrowser();
+  const initialFrameloader = initialBrowser.frameLoader;
+  const initialRemoteTab = initialFrameloader.remoteTab;
+
   recording.on("unusable", function(name, data) {
     pingTelemetry('record-button', 'unusable', data);
 
@@ -1781,6 +1785,12 @@ function onRecordingStarted(recording) {
     browser = getBrowser();
     const recordingId = data.id;
 
+    console.log("COMPARISON:", {
+      sameBrowser: initialBrowser === browser,
+      sameFrameloader: initialFrameloader === browser.frameLoader,
+      sameRemoteTab: initialRemoteTab === browser.frameLoader.remoteTab,
+    });
+
     // When the submitTestRecordings pref is set we don't load the viewer,
     // but show a simple page that the recording was submitted, to make things
     // simpler for QA and provide feedback that the pref was set correctly.
```
and running with that patch I made one recording normally, and another where I started the recording, dragged the tab into a new window, and then stopped the recording, and the output was
```
console.log: "COMPARISON:" ({sameBrowser:true, sameFrameloader:true, sameRemoteTab:true});
console.log: "COMPARISON:" ({sameBrowser:false, sameFrameloader:true, sameRemoteTab:true})
```

**Comment by ryanjduffy** [comment]
I think there is _some_ consistency but not end to end. I'll confirm on Monday but I think I saw it break down in `reloadAndRecordTab` due to `tabbrowser.updateBrowserRemoteness` which (i think) creates a new frameLoader and remote tab. That's manageable but wanted to see if there was a consistent reference independent of those.

**Comment by ryanjduffy** [comment]
Sadly, I have to bump this to next week because this week was consumed with getting the build working again on the M1. But, now that it _is_ working, this should be doable!

**Comment by ryanjduffy** [comment]
This is improved by #445 but additional work is required to implement the new visuals described above. Hoping to still tackle that this week.

**Comment by ryanjduffy** [comment]
Noting the #445 landed a bit ago. I've opened #446 for some technical follow up from it. Will keep this open for a bit longer to track the visual improvements above.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-48](https://linear.app/replay/issue/RUN-48/improve-the-record-button-transition-states)
