### ISSUE TITLE
Cannot record chat.mozilla.org

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#432]
It looks like this replay is trying to use webassembly

https://replay.io/view?id=1b807efd-a9d5-4d20-a87c-dd257c79bcbf

**Comment by bhackett1024** [comment]
We support wasm, but not wasm streaming on firefox --- wasm streaming uses spidermonkey's thread pool which we allow to behave differently when recording vs. replaying.  The best fix here is to stop treating this thread pool in special ways and just record its behavior all the time, though we'll need to run these tasks either on the main thread or add another thread pool for non-deterministic tasks (something we'll want at some point anyways, e.g. convenience methods in the driver).

Incidentally we support wasm streaming on chrome, because we don't have any special cased non-deterministic threads there.

**Comment by ryanjduffy** [comment]
Duping this out to #501 which includes @bhackett1024's suggested approach
