### ISSUE TITLE
Open the Google Login in the user's preferred browser

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/gecko-dev#518]
We should consider configuring the login process for Replay to use the user's preferred browser to build trust that their credentials are secure.

https://app.intercom.com/a/apps/k7f741xx/inbox/inbox/search/conversations/165083900017937?teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all&userIds=%5B%2261435bef2c192fff28865827%22%5D

**Comment by ryanjduffy** [comment]
Good point, @jasonLaster. That's also what I had in mind.

**Comment by arcataroger** [comment]
(Feedback submitter here)

The problem with opening it in Replay is that it requires the user to hand over their Google credentials to a relatively unknown 3rd-party app. It's one thing to use Google to provide a token to login to Replay, but typing in the password into the app opens it up to MITM password capture. Not that I distrust Replay any more than any other app, but our Google accounts are tied to so much these days that it's just not a good practice to share that password with other apps.

Plus, if the Replay browser is built off Firefox, it may not support (I'm not sure) some Google authentication procedures, such as some of the proprietary tap-to-login 2FA methods and security keys supported by Chrome for accounts who have Advanced Protection enabled. This situation may have gotten better since the last time I tried it, but it was a blocker to logging in just a year or two ago.

Ideally it would be handled the way the Postman desktop app does it: Opening a login window in the user's default browser's most recent profile, using their already-saved credentials or password manager, and then passing a login token/callback URL back to your own app. That way you get the login token but never the password.

I don't know if this is relevant, but the Apple docs discuss this workflow: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession

Safari should not open unless it's the default browser. On macOS you're not limited to Safari the way you are on iOS webviews.

**Comment by ryanjduffy** [comment]
WIP

- [ ] RecordReplay/gecko-dev#641
- [ ] RecordReplay/devtools#4870
- [ ] RecordReplay/backend#4008

**Comment by ryanjduffy** [comment]
Auth is _sometimes_ flowing from the browser to the app now. It sometimes fails and I don't know why. Also, I think we'll have to keep support for the previous flow for a while since we can't guarantee when users will upgrade their browser. So a bit more to do but progress.

https://www.loom.com/share/c46190cf6d6d44a2840b2f47bba7d99d

**Comment by ryanjduffy** [comment]
Sequence Diagram for the current end-to-end flow:

![image](https://user-images.githubusercontent.com/788456/147532508-82f675f3-901f-46d8-aee9-eac6535eb052.png)

https://excalidraw.com/#json=Ikm4opzfId8Y6pwOvN766,tkpxISP3ltkZ6t7nZjO-Eg

**Comment by ryanjduffy** [comment]
Download link for the branch linked above (`ryan/browser-auth`): https://static.replay.io/downloads/macOS-gecko-20211228-74ec5733ec3e-a6a730607978.dmg
