### ISSUE TITLE
Improve Replay platform warnings

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#523]
The new platform warnings do a great job of letting people know that the recording might playback differently or not work at all, but a couple of things can be improved:

1. We can polish when and how the warning is shown
2. We can treat some warnings like MediaPlayback as not as severe
<img width="1318" alt="Screen Shot 2021-09-20 at 6 58 25 AM" src="https://user-images.githubusercontent.com/254562/134015323-b78919d9-e2bc-4106-8677-f9f9df2d79fb.png">
<img width="1318" alt="Screen Shot 2021-09-20 at 6 58 17 AM" src="https://user-images.githubusercontent.com/254562/134015342-6955469e-5c0b-427c-bb43-9f05dd9288d5.png">

**Comment by jonbell-lot23** [comment]
**Design POV:**

![image](https://user-images.githubusercontent.com/9154902/134108581-77f60046-512f-4480-af81-fe55b0d7c9d2.png)

1. Let's Replace the robot with a Replay logo
2. As Jason mentioned, let's not show the banner for every issue. Only high priority ones.

![image](https://user-images.githubusercontent.com/9154902/134108762-ceb23984-e651-4670-a90b-016ec6158be4.png)

3. Let's not show the banner on the upload screen. Instead...
4. ... let's put text into the upload screen itself. We can work on the link, text, and visual treatment later on.

![image](https://user-images.githubusercontent.com/9154902/134109419-444c1914-e16f-4b85-8d51-6b7df535fc16.png)

5. When you go into the Replay itself, the banner stays at the top. It shouldn't. It should only appear on the page you're recording.
6. It's important that we at least show a grey box of the thing we weren't able to record, as shown here

![image](https://user-images.githubusercontent.com/9154902/134109494-dcb1c186-fd42-4578-9aea-460e115bb589.png)

7. We should also have a responsively designed error message because sometimes divs are small. So this is an alternate treatment for use in that case.

**Comment by jasonLaster** [comment]
Couple of thoughts:

1. I think it would be better to show the warning in the upload screen and replay. If we want to show a warning while recording it should be less obtrusive, like a badge next to the recording button.
2. The warning in the upload screen should mention the missing feature
3. I like the idea of contextual warnings, but some wont correspond to a DIV and even if they do that is more work. Is there another place we can show it? I think i'm missing a basic replay info section 😉

**Comment by jonbell-lot23** [comment]
1. I figured we could keep it around for the high priority items, but I'm happy to drop in all cases from the browser.
2. Agree, exact text to come.
3. I think the inline message is really important. But yeah, we could:
* Put it in the console
* Put it in the first frame of the video pinned into a corner or something
* Replay info section is good ... but it's secondary because most people won't go looking for it there

**Comment by jonbell-lot23** [comment]
@ryanjduffy Sounds like these are the steps we're going to take here:

1. Take the banner out of the browser entirely. Ship it. This shouldn't be blocked on the other items.
2. Then we'll come up with some text for the upload screen. Ship that. No reason to wait on the other items.
3. Finally, we'll come up with ways of badging in the interface itself. The ideal UX answer is to show people what they're missing inline on the page where possible. You should never be looking at a big white page without understanding why, nor should you have to go digging for some error message somewhere in the library or an info screen. But that may take some time, and we'll explore other options in parallel.

#shipit!

**Comment by bhackett1024** [comment]
I have some serious concerns with this proposal:

1. The reason for showing people the banner while recording is because that is when the website won't be working.  If we wait until the upload screen to message them then that is well after the point where they start becoming confused.  It's important that we tell people quickly why their page isn't working as expected, not least to avoid a ton of bug reports about things that break when recording.

2. Badging in the interface isn't really practical for several reasons.  First, most of the APIs we are disabling are JS APIs.  If an exception gets thrown there isn't any reasonable way to determine what effect that has on the page or how it is displayed.  Maybe the screen goes white, maybe it looks fine, maybe it does one of a million other things.  Second, for disabled DOM features like media elements, the page may replace the element with something else if it can't render, and there isn't any place for the badge.

**Comment by jonbell-lot23** [comment]
I hear you @bhackett1024 -- I think the key here is "over-warning" versus "under-warning." We don't want to be alarming when actually the Replay is going to work great. And obviously we don't want to have an entire page break quietly. So the key is finding a balance between the two.

I understand your points about badging the UI not being feasible. I imagine a world where we do it where possible (like an obvious webGL region/div/whatever) and then lean on other messaging (like in the browser, upload screen, banner in Replay playback, etc) for the other places. I understand 100% isn't doable, but are there some low hanging fruit examples that are doable alongside the stuff that's not?

It sounds like the next steps are going to come down to finding that balance between under- and over-reporting. I share Jason's view that not *everything* requires a huge yellow banner across the top. But I also share Brian's view that removing the banner in 100% of cases means that some pages will be fundamentally broken and that needs to be messaged more clearly.

If we had a list of failures we consider critical versus less critical, that might help us find a way forward?

**Comment by jasonLaster** [comment]
Thanks @jonbell-lot23 

Agreed that severity is important. And if the recording experience could be bad then we should notify earlier rather than later.  

Here are the cases we currently handle [issue](https://github.com/RecordReplay/gecko-dev/commit/dc9936175e393ff0a2c104756c46ee32867ef923): MediaPlayback, WebGL, WebAudio, WebRTC, LoadPlugin, SharedArrayBuffer, and WasmStreaming.

* I've never seen an issue where users are affected by MediaPlayback
* I've seen users work around WebGL issues
* I've seen WasmStreaming and WebAudio be show stoppers
* I don't have any examples for WebRTC, LoadPlugin, SharedArrayBuffer

Here's what I propose:

1. low severity: MediaPlayback we warn users on the upload screen and replay ui
2. everything else: we design a more professional banner that is shown while recording and is replaced with a warning on the upload screen and replay ui. 


[figma](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=6749%3A41060)
<img width="1563" alt="Frame 4" src="https://user-images.githubusercontent.com/254562/134775907-83ebc595-b951-427a-ad1b-6b9a756603e0.png">

**Comment by jonbell-lot23** [comment]
Thanks Jason, I like both ideas.

* So once we agree on severe versus not severe...
* We make a subtle visual treatment for the top banner in browser
* We keep the upload screen concept
* And we design how it should look on Replay -- in theory the visual treatment should be similar

**Comment by jonbell-lot23** [comment]
Ah ha, it looks like Replay has light/dark themes, so here was my exploration:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/9154902/134850629-e156c144-8d1b-4298-b40d-1a6647706982.png">

The goal is to keep a colour that aligns with the browser's current colour. (I assume this is possible somehow) Then we have a little note at the top. We can play with the exact colours and text, but this is what I'd propose we work towards.

**Comment by jonbell-lot23** [comment]
Ok, I think this is just about ready to tackle.

1. Use the light/dark visuals above at the browser level. (Replacing the big bright yellow banner we currently have)
2. Add a note into our upload screen.
3. There's still a question of high importance/low importance that Jason mentioned above. His thinking there seems like a good place to start from.

Cc'ing @ryanjduffy , who's doing this I believe?

**Comment by ryanjduffy** [comment]
I've started looking into the notification styling in the browser. That should be pretty straightforward. I'm not as clear on how we message on the upload screen yet.

@bhackett1024 , @loganfsmyth - do we have this information already in the recording metadata? Should we/do we need to add it?

We could pass the context via querystring parameter to the upload screen as a lo-fi solution but that'd be lost if the user bailed on the upload and came back to it later. Metadata seems better if that's possible.

**Comment by bhackett1024** [comment]
We don't include unsupported information in the recording metadata, but it should be straightforward to do so.  The Recording class in connection.js both gets the unsupported feature notifications and sends the `Internal.setRecordingMetadata` commands to associate metadata with the new recording.

**Comment by ryanjduffy** [comment]
There are a couple more parts to this beyond restyling the banners so I'm reopening to address those.

**Comment by ryanjduffy** [comment]
The metadata changes required for the remaining work seems to be larger than we want to do without more discussion and prioritization. I've created https://github.com/RecordReplay/backend/issues/3196 to track that work and will close this. We can spin up new tickets off that project once we have an approved path forward.
