### ISSUE TITLE
Replay branding is gone

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#545]
Likely a result of the recent change @ryanjduffy made
<img width="1605" alt="Screen Shot 2021-10-02 at 9 08 35 AM" src="https://user-images.githubusercontent.com/254562/135724224-3cccb6c5-0082-4295-b611-84db93296d4e.png">

**Comment by ryanjduffy** [comment]
Was this from a new  install or an update?

**Comment by jasonLaster** [comment]
an update

**Comment by ryanjduffy** [comment]
I think this is due to having created a profile with a theme config before we started using alpenglow as the default. When I install replay fresh, it launches with alpenglow and stays that way. When I launch my local build with a new profile, i can see that the first run only has the default theme enabled but that our code causes it to enable and use alpenglow. On the second launch, all 4 themes are available but alpenglow is the enabled one.

All this to say, I think this is just a bug for us and very early users and probably not something we need to fix by reverting support for changing the theme.

**Comment by jasonLaster** [comment]
Makes sense!
