### ISSUE TITLE
Show new replay tab immediately

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#556]
We currently show a spinner when the user clicks "stop". We have telemetry on how long the spinner takes, but short story, it too often takes more than 10 seconds which is unacceptable. 

We should figure out how to open a new tab immediately with the new replay's url `/recording/<id>`

**Comment by jonbell-lot23** [comment]
And piping up from design-land: every feature should be built with this mindset as well.

We can't ever assume "it will probably load quickly" because then the experience gets caught up in a million little things that can go wrong. We should always load something immediately and message status. (As this task describes) If the feature loads quickly 99% of the time, great. But when it doesn't, we can at least provide messaging. #uxresiliency

**Comment by kannanvijayan** [comment]
Taking some notes on things to check:

1. What does the browser wait for before it stops the spinner on the REC button and opens a new tab.

I don't think it's waiting on recording upload to finish (that would consistently take very long times), but would be good to double-check.

It could be waiting on the result of the `RecordingMetadata` protocol command to come back, which I can see taking a long time if the backend is congested.

**Comment by jasonLaster** [comment]
Here's some telemetry @ryanjduffy added a month ago

https://ui.honeycomb.io/replay/datasets/backend/result/3vBXySvALSh?tab=raw
https://github.com/RecordReplay/gecko-dev/blob/webreplay-release/devtools/server/actors/replay/connection.js#L692

e.g.
```js
pingTelemetry("recording", "finished", { action: "updateBrowserRemoteness", recordingState });
```

There's tons of `pingTelemetry` here, but it's not clear what we should be looking for... perhaps `RecordingState.Ready` with a `duration`...

**Comment by ryanjduffy** [comment]
@kannanvijayan Here's a honeycomb query for the relevant durations:

https://ui.honeycomb.io/replay/datasets/backend/result/n4HtVhAojFx

The time from clicking stop to finishing is actually pretty consistent but the starting times vary a lot for periods and then stabilize. This'll be a fun one!

**Comment by kannanvijayan** [comment]
I'm not sure how to interpret the categories.  What are the various groupings here?

Is the time from "clicking stop" to "finishing" equivalent to the time it takes for the user to see the new tab after clicking "stop"?

What start times are being plotted there?

**Comment by ryanjduffy** [comment]
They should be measuring the time between the "STOPPING" state (when the user clicks the button) and when it's saved. But, looking at the code it seems like it's tracking from STOPPING to "finished" instead of "saved".

There's this line of invalid code which is calculating the `duration` but then throwing it into the aether because that method doesn't support a third argument.

```js
  // defer setting the state until the end so that the new tab has opened before the spinner disappears.
  setRecordingState(key, RecordingState.READY, {duration: getRecordingStateDuration(key, RecordingState.STOPPING)});
```

There should be one of these in there:

```
  pingTelemetry("recording", "saved", { action: "complete", duration: getRecordingStateDuration(key, RecordingState.STOPPING) });
```

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-241](https://linear.app/replay/issue/RUN-241/show-new-replay-tab-immediately)
