### ISSUE TITLE
Unexpected type error in recording

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/gecko-dev#588]
This recording shows an error, `Unexpected Type`, that only happens in Replay. I searched through the code in the replay and didn't see an apparent cause there which leads me to think the browser is throwing it from somewhere.

https://app.replay.io/recording/047a1b8e-8077-4176-a925-9b424c7f94fd?point=55817191231155286934282395847755245&time=27085&hasFrames=true

**Comment by ryanjduffy** [comment]
@bhackett1024, @loganfsmyth  I added a few comments to a new replay of this issue. It only happens when recording; the app works as expected when just browsing. Ideas?

https://app.replay.io/recording/0570909a-94f9-408b-bd38-280968bca7f9

**Comment by bhackett1024** [comment]
This error looks like the one fixed in https://github.com/RecordReplay/backend/issues/3095, which was affecting unqork users.  Previously we would crash while recording the site.  The exception gets thrown from here:

https://github.com/RecordReplay/gecko-dev/blob/69d95c6857a6bd5bbc3864048390b75edb76d380/js/src/vm/Interpreter.cpp#L4642

What's going on is that spidermonkey is trying to get a property from a value, and it sees a type it doesn't expect and throws an exception (it used to crash instead).  From the recording here it's pretty clear to me what unexpected value type it is seeing: the magic arguments.  Magic arguments are a spidermonkey optimization (which IIRC I originally designed/built, though it's changed significantly since then) where arguments objects which are only accessed in certain ways --- arguments[i], arguments.length --- do not have to be materialized into an actual object, but use a special magic value that represents the arguments for the current function.

It looks like that optimization is being performed incorrectly here.  The `Tooltip` function caller passes `arguments` into `__storybookClass`, where those arguments have a length of 2.  It looks like the magic arguments value is being used (incorrectly) there, because the `__storybookClass` callee thinks the `args` value passed in has a length of 1, i.e. it's the arguments to the `__storybookClass` call itself.  It tries to then read the `__storybookClass` property from the magic arguments, and the exception gets thrown because we're not supposed to access that property on magic arguments values.

One simple way to "fix" this would be to return undefined when getting random properties from the magic arguments value, but this wouldn't be a correct fix.  There is a semantics problem where passing in the magic arguments value to `__storybookClass` causes it to behave incorrectly, i.e. it reads the wrong length on the value and ends up looking for the `__storybookClass` property on the wrong object.  It would be better to fix this properly by figuring out what is going wrong with the optimization and fixing that.  Note that disabling this optimization entirely wouldn't be great, as it's important for perf --- frameworks like storybook generally make heavy use of arguments objects.

A couple questions:

* Are there reliable STR for this error?

* Does this still show the error when using the replay browser but not recording?

**Comment by bhackett1024** [comment]
Also, I don't see any crashes related to this in bugzilla, so rebasing on a recent firefox probably won't fix this.  It also suggests it could be a recording related problem.

**Comment by ryanjduffy** [comment]
Thanks for the explanation! Very helpful. 

* I can repro it every time when recording on the unqork QA site
* It only repros when recording. The site behaves correctly otherwise in the Replay browser.

**Comment by bhackett1024** [comment]
> Thanks for the explanation! Very helpful.
> 
>     * I can repro it every time when recording on the unqork QA site
> 
>     * It only repros when recording. The site behaves correctly otherwise in the Replay browser.

Cool, can you write down some exact STR?  I don't know what the unqork QA site is.

**Comment by ryanjduffy** [comment]
I'll have them add your replay email to it so you can access.

1. Visit qa4.unqork.io
2. Log In
3. Try to record

**Comment by bhackett1024** [comment]
Thanks, the arguments analysis is definitely behaving differently when recording vs. not recording.  When not recording it decides the Tooltip function needs a real arguments object, but when recording it decides the Tooltip function can have optimized arguments.

**Comment by ryanjduffy** [comment]
@bhackett1024 :+1: Let me know when the browser has been updated and I'll follow up with the unqork team. Thanks!

**Comment by bhackett1024** [comment]
> @bhackett1024 👍 Let me know when the browser has been updated and I'll follow up with the unqork team. Thanks!

New browsers have been released with the fix.  I also verified that recording this site works now.
