### ISSUE TITLE
Connection has not been authenticated

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#598]
The Replay browser can occasionally get into a bad state where you cannot record. Ryan fixed this by clearing his API Key, but Jon also hit the issue and i dont think he has an API Key. I get out of the issue when i see it by quitting and re-opening.

https://ui.honeycomb.io/replay/datasets/backend/result/dLXvB9fen1M

![image](https://user-images.githubusercontent.com/254562/142800566-43e02240-0449-4320-a7d4-b05b89a9ee81.png)

**Comment by hbenl** [comment]
While working on this, I suddenly ended up with my Replay browser in this state (immediately after logging out on app.replay.io):
![Screenshot_2021-11-23_13-28-57](https://user-images.githubusercontent.com/16060807/143037428-d9d8c984-b7d6-429d-aadf-959b8572e698.png)
So I was not logged in but the "REC" button was enabled. I also checked that `devtools.recordreplay.user-token` was empty in `about:config`.
I don't understand how this could happen, we have 2(!) mechanisms for updating the "REC" button when `devtools.recordreplay.user-token` changes: using an [observer](https://github.com/RecordReplay/gecko-dev/blob/1062976ee0ed0ac4c23380251c4ca86d56462331/devtools/startup/DevToolsStartup.jsm#L1455-L1457) and, as a fallback, using [polling](https://github.com/RecordReplay/gecko-dev/blob/1062976ee0ed0ac4c23380251c4ca86d56462331/devtools/startup/DevToolsStartup.jsm#L1531-L1534).

**Comment by hbenl** [comment]
IIRC this happened immediately after updating the browser: I logged in on app.replay.io, then was prompted to update the browser and did so, then logged out.
I could also reproduce this (logging in and out without the "REC" button changing its state), but after restarting the browser I could not reproduce it anymore.

**Comment by hbenl** [comment]
I tried on another computer: Logged in on app.replay.io, updated the browser, logged out on app.replay.io.
Result:
![Screenshot_2021-11-23_15-31-34](https://user-images.githubusercontent.com/16060807/143043623-594f493e-d531-4558-9c11-aac004bdea66.jpg)
Once again the "REC" button is enabled but there's no access token. So it seems this could really be related to browser updates.

**Comment by hbenl** [comment]
Seeing several of these error messages in the browser console:
![Screenshot_2021-11-23_15-38-38](https://user-images.githubusercontent.com/16060807/143044507-61201b70-aaea-4591-bf8b-9fc9cd692aff.jpg)
... but then I found that these error messages also appear when the browser is not in this broken state. In fact all the error messages stay the same.

**Comment by hbenl** [comment]
I can still make a recording with the browser in this state, so I guess it keeps using the access token that I had before logging out.
But if my token _expired_ after a browser update (instead of it getting deleted because I logged out), the browser would try to upload the recording with the expired token, which would lead to the error message seen in the OP.

**Comment by hbenl** [comment]
The root cause of this issue is that we use the `RECORD_REPLAY_API_KEY` environment variable for 2 purposes:
- it is set by the user if he wants to use an API key
- it is [set by the browser itself during initialization](https://github.com/RecordReplay/gecko-dev/blob/e47c146b6e0e625d290a6e7bf7743829dc9f7017/devtools/server/actors/replay/connection.js#L363) to the user's token (in order to pass it to [this code](https://github.com/RecordReplay/gecko-dev/blob/e47c146b6e0e625d290a6e7bf7743829dc9f7017/toolkit/recordreplay/ProcessRecordReplay.cpp#L311) I guess)

When the browser restarts itself after an update (which you can simulate using `about:restartrequired`), this environment variable keeps its value. Now the browser's initialization code thinks that the environment variable was set by the user and contains an API key (not a token), which never expires and should override any user token.

**Comment by jasonLaster** [comment]
> When the browser restarts itself after an update (which you can simulate using about:restartrequired)

This is big!
