### ISSUE TITLE
Disable recording while also profiling

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#702]
It's possible for a user to be both profiling and recording. We should find a way to disable that use case and then message to the user.

**Comment by kannanvijayan** [comment]
Bumping this and prioritizing it.

I saw another couple crashes occurring _today_ with basically the same stack signature, in a different recording by a different user.  Speaking with the user, he confirmed that he didn't explicitly enable profiling during the recording, so this seems to be some side-path via which profiling can get enabled.

We should simply disable profiling entirely on our browser.  We disable other devtools and this gecko profiler infrastructure serves no purpose without that.

The fix should be relatively straightforward: just return early from the `GeckoProfilerRuntime::enable` implementation.

**Comment by jasonLaster** [comment]
@kannanvijayan if it's alright - we should also condition it on currently recording. It is fine to use the profiler or devtools if you're not recording.

**Comment by kannanvijayan** [comment]
Benoit brought up the fact that the profiling can be turned on _before_ recording is started.  However, it may be the case that this doesn't matter because we kick off a new content process for recording anyway, which shouldn't start with profiling enabled, but I don't know enough about the implementation to be sure of that.

I think your suggestion works fine, so I'll go with that, but we may need to come back and disable it globally.

**Comment by jasonLaster** [comment]
I like your change!
