### ISSUE TITLE
Support react devtools in playwright

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#716]
Currently recordings made with our gecko/playwright browser don't contain the react devtools backend.

**Comment by hbenl** [comment]
Currently we only add the react devtools backend to the *first* global (i.e. window) object:
https://github.com/RecordReplay/gecko-dev/blob/4a46d8d2767e9043b4c94224d8c591ce464bfaf7/devtools/server/actors/replay/module.js#L469-L474
In our regular browser, the first global is the window object of the page to be recorded, but when recording with playwright, it is the window object of an `about:blank` page, before playwright navigates to the page to be recorded.
This also means that react devtools will not work in our regular browser after navigating to a new page (try starting a recording with `about:blank` and then navigate to `https://app.replay.io` - in the recording you can see that only the window object for `about:blank` contains `__RECORD_REPLAY_REACT_DEVTOOLS_SEND_BRIDGE__`, but not the window object for `https://app.replay.io`).
I don't know what the reason was to only add the react devtools backend to the first global (maybe to avoid adding it to iframes?), but I would suggest that we add it to every "top" global (i.e. if `window.parent === window`) that has a http(s) URL (to avoid adding it to `about:blank` or to background pages from WebExtensions (playwright includes such a background page)).
@bhackett1024 what do you think?

**Comment by bhackett1024** [comment]
That sounds good to me, I actually just ran into this while working on https://github.com/RecordReplay/gecko-dev/pull/844 and just added the backend to all globals, but if there's a more appropriate filter that would be better to do.  I don't know why we only add it to the first global.  One thought is that the frontend might not be able to reliably distinguish backend messages coming from different globals because we don't include any sort of window ID, so if different windows have different react renderers which use the same rendererID then we'll conflate them.  This seems like it wouldn't be hard to fix though, and it would definitely be best if we could reliably detect all react code which is running under any global in the recording.

**Comment by bhackett1024** [comment]
I backed out the associated changes from #844 (which I didn't really intend to land as part of that PR) so that we can focus on developing the right fix for this problem here.
