### ISSUE TITLE
Remove Adobe Acrobat install message from Replay

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#752]
![image](https://user-images.githubusercontent.com/9154902/158289195-dd8b2578-43a3-4326-8fe1-0484302fd2d6.png)

We know we're based on Firefox, so we understand why we're seeing Acrobat messages. But to a user, this feels like a strange thing to see because Adobe Acrobat has nothing to do with Replay technology. We should suppress or remove this.

**Comment by jonbell-lot23** [comment]
Re-upping this item. This is pretty much the first thing a user sees on their Replay journey and it's confusing/unprofessional. We should prioritise suppressing it.

**Comment by gideonred** [comment]
I've placed this in "To Discuss" for next sprint. That'll make sure we chat about it.

**Comment by gideonred** [comment]
How to reset a Replay browser to reproduce this:

1: delete the Replay browser from /Applications
2: Go to ~/Library/Application Support/ and delete the Replay directory
3: Re-download

**Comment by gideonred** [comment]
Mmm... I'm not seeing this behavior after resetting my browser.

**Comment by jonbell-lot23** [comment]
> Mmm... I'm not seeing this behavior after resetting my browser.

Bummer. I guess the next step is finding where in our gecko-dev code we trigger this? Let me know if I can help, my browser does show the behaviour.

**Comment by gideonred** [comment]
I just volunteered my wife's macbook which has never had Replay on it and after installing it, it did not show the Adobe thing.

**Comment by gideonred** [comment]
> my browser does show the behaviour.

Interesting, let me see what I can see.

**Comment by gideonred** [comment]
I can see why Jon currently has this notification, in his `Profiles/a7bkpjpc.dev-edition-default/extensions.json` file the Adobe Acrobat extensions is listed with `"seen": false`.

Based on my testing it seems we have stopped installing this extension so new users wont run into it. Older users who haven't dismissed the notification, will keep seeing it.

Because new users won't see it, I believe this isn't an issue anymore.
