### ISSUE TITLE
Playwright browser doesn't send telemetry

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#782]
Our Playwright/Firefox browser doesn't send telemetry events because the `replay.telemetry.url` and `replay.telemetry.enabled` prefs are missing: they are set in the `firefox-branding.js` file that isn't loaded by the Playwright browser.
This causes more issues than just missing telemetry: `pingTelemetry()` *throws* when it tries to read the prefs. I've noticed this because Playwright currently doesn't write sourcemaps to disk because of that.

**Comment by ryanjduffy** [comment]
@bhackett1024 - Was it intentional to omit the branding from the playwright build? Did it conflict in some way?

If not, I'll update the build to use it and that should resolve this.
If so, we can add that pref in some other way.

WDYT?

**Comment by bhackett1024** [comment]
Yes, not having branding on the playwright build is intentional.  A branded build has different path names and a different main executable name which makes it harder / impossible to use with different automation frameworks.  I know that cypress is affected by this, and I think playwright is as well because browser directories are specified rather than paths to the main executable.

**Comment by ryanjduffy** [comment]
:+1: I think we'll be working around this with the new plugin-based architecture but we're not there yet so I'll stick with no branding.
