### ISSUE TITLE
Replay breaks app behavior while recording a CodeSandbox that uses a mock service worker for a request

### ISSUE THREAD

**Issue by markerikson** [replayio/gecko-dev#849]
Trying to do some test recordings using the "Redux Essentials" final CodeSandbox example app at https://qywxv.csb.app/ .

The app loads fine in FF normally, but when I hit "Record" and the page refreshes, the app fails to load.  If I make sure FF's DevTools are open first, I see these error messages in the console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://codesandbox.io/api/v1/sandboxes/qywxv. (Reason: CORS request did not succeed).

Failed to load ‘https://codesandbox.io/api/v1/sandboxes/qywxv’. A ServiceWorker passed a promise to FetchEvent.respondWith() that resolved with non-Response value ‘undefined’. [mockServiceWorker.js:270:15](https://qywxv.csb.app/mockServiceWorker.js)
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

![image](https://user-images.githubusercontent.com/1128784/168652522-c51c66d7-c6ef-4b6b-9d35-ea8fa48b6121.png)

So, there's some kind of difference in behavior between just loading the page in FF, and actually trying to _record_ the page.

As additional background, this app specifically uses the Mock Service Worker package ( https://mswjs.io/ ) to mock out API requests.

**Comment by bhackett1024** [comment]
Could this be related to the operations we do to record network requests / service worker behavior, similar to https://github.com/RecordReplay/customer-support/issues/63 ?  cc @loganfsmyth @jcmorrow

**Comment by loganfsmyth** [comment]
That could certainly be, we'll have to dig in more to be sure.

**Comment by jasonLaster** [comment]
added this to the May 26th sprint. feel free to change

**Comment by loganfsmyth** [comment]
Disabling all our logic for network request tracking does not appear to fix this, so may be harder to track this down.

From what I can see, the CORS request is failing because when recording, the OPTIONS request has
```
Access-Control-Request-Headers: alt-used,authorization
```
but when not recording it is
```
Access-Control-Request-Headers: authorization
```

Codesandbox does not return `Access-Control-Allow-Origin` in the first case and does in the second, so the first one causes the request to fail. I don't know why we're getting that `Alt-Used` header in one case but not the other.

I have not looked into the later errors too closely, but with the way the mockServiceWorker.js code is written, it _is_ possible for the JS code to legitimately return `undefined` instead of a response, so I'm tentatively speculating that the second and third error are maybe just caused by the first one, but hard to be sure.

**Comment by gideonred** [comment]
Deprioritization this at the moment since it seems to happen not very often.

**Comment by jasonLaster** [comment]
Added a P3 label so that we can surface low-priority issues.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-293](https://linear.app/replay/issue/RUN-293/replay-breaks-app-behavior-while-recording-a-codesandbox-that-uses-a)
